spring:
  datasource:
    username: toyville
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://postgres:5432/toyville

  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    open-in-view: false

  data:
    rest:
      base-path:  /v1

#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB

  output:
    ansi:
      enabled: always

#server:
#  use-forward-headers: true
